#!/usr/bin/env bash

set -o errexit
set -o errtrace
set -o nounset
set -o pipefail


# Find root directory
root="$(git rev-parse --show-toplevel)/infra"
cluster_root="${root}/cluster"


# Delete cluster
ctlptl delete -f "${cluster_root}/cluster.yaml"
