version: 2.1

jobs:
  build:
    machine:
      image: ubuntu-2004:202111-01
    environment:
      BAZEL_SHA: 399eedb225cff7a13f9f027f7ea2aad02ddb668a8eb89b1d975d222e4dc12ed9
    working_directory: ~/project
    steps:
      - checkout:
          path: ~/project
      - restore_cache:
          keys:
            - '{{ checksum ".circleci/config.yml" }}-{{ .Branch }}'
            - '{{ checksum ".circleci/config.yml" }}-main'
      - run:
          name: Configure path
          command: |
            mkdir -p bin
            echo 'export PATH="${CIRCLE_WORKING_DIRECTORY}/bin:${PATH}"' >> $BASH_ENV
      - run:
          name: Install Bazel
          command: |
            if [ ! -f bin/bazel ]; then
              curl -sfSL -o bin/bazel https://github.com/bazelbuild/bazel/releases/download/5.0.0/bazel-5.0.0-linux-x86_64
              echo "${BAZEL_SHA}  bin/bazel" | sha256sum -c
              chmod u+x bin/bazel
            fi
      - run:
          name: Print Bazel version
          command: |
            bazel version
      - run:
          name: Build
          command: |
            bazel build --disk_cache=~/.cache/bazel //...
      - save_cache:
          key: '{{ checksum ".circleci/config.yml" }}-{{ .Branch }}'
          paths:
            - "bin"
            - "~/.cache/bazel"
      - run:
          name: Test
          command: |
            bazel test --disk_cache=~/.cache/bazel //...
      - save_cache:
          key: '{{ checksum ".circleci/config.yml" }}-{{ .Branch }}'
          paths:
            - "bin"
            - "~/.cache/bazel"

workflows:
  version: 2
  pipeline:
    jobs:
      - build:
          name: build
