version: 2.1

jobs:
  build:
    parameters:
      bazelisk_version:
        type: string
        default: v1.12.2
    machine:
      image: ubuntu-2004:202111-01
    working_directory: ~/project
    steps:
      - checkout:
          path: ~/project
      - restore_cache:
          name: Restore Bazelisk
          keys:
            - bazelisk-<< parameters.bazelisk_version >>
      - restore_cache:
          name: Restore Bazel
          keys:
            - bazel-{{ checksum ".bazelversion" }}
      - restore_cache:
          name: Restore build cache
          keys:
            - 'disk-cache-{{ .Branch }}-{{ .BuildNum }}'
            - 'disk-cache-{{ .Branch }}'
            - 'disk-cache-main'
      - run:
          name: Configure path
          command: |
            mkdir -p ~/bin
            echo 'export PATH="~/bin:${PATH}"' >> $BASH_ENV
      - run:
          name: Install Bazelisk
          command: |
            if [ ! -f ~/bin/bazel ]; then
              curl -sfSL -o ~/bin/bazel https://github.com/bazelbuild/bazelisk/releases/download/<< parameters.bazelisk_version >>/bazelisk-linux-amd64
              chmod u+x ~/bin/bazel
            fi
      - save_cache:
          name: Save Bazelisk
          key: bazelisk-<< parameters.bazelisk_version >>
          paths:
            - "~/bin/bazel"
      - run:
          name: Print Bazel version
          command: |
            bazel version
      - save_cache:
          name: Save Bazel
          key: bazel-{{ checksum ".bazelversion" }}
          paths:
            - ~/.cache/bazelisk
      - run:
          name: Build
          command: |
            bazel build --disk_cache=~/.cache/bazel-disk-cache --repository_cache=~/.cache/bazel-repository-cache //...
      - run:
          name: Test
          command: |
            bazel test --disk_cache=~/.cache/bazel-disk-cache --repository_cache=~/.cache/bazel-repository-cache //...
      - save_cache:
          name: Save disk cache
          key: 'disk-cache-{{ .Branch }}-{{ .BuildNum }}'
          paths:
            - "~/.cache/bazel-disk-cache"
            - "~/.cache/bazel-repository-cache"

workflows:
  version: 2
  pipeline:
    jobs:
      - build:
          name: build
