load("@bazel_tools//tools/build_defs/repo:http.bzl", "http_archive")
load("@bazel_tools//tools/build_defs/repo:utils.bzl", "maybe")


_RULE_DEPS = [
    # The following can be manually generated by inspecting pipenv dependencies, and checking the wheel links at pypi.org
    (
        "pipenv",
        "https://files.pythonhosted.org/packages/94/6c/c0a2f56a628d1258ac0175647ab18ee73fa0870dc0fcaa33e9be079e5fb0/pipenv-2022.1.8-py2.py3-none-any.whl",
        "3b80b4512934b9d8e8ce12c988394642ff96bb697680e5b092e59af503178327",
    ),
    (
        "certifi",
        "https://files.pythonhosted.org/packages/37/45/946c02767aabb873146011e665728b680884cd8fe70dde973c640e45b775/certifi-2021.10.8-py2.py3-none-any.whl",
        "d62a0163eb4c2344ac042ab2bdf75399a71a2d8c7d47eac2e2ee91b9d6339569",
    ),
    (
        "distlib",
        "https://files.pythonhosted.org/packages/ac/a3/8ee4f54d5f12e16eeeda6b7df3dfdbda24e6cc572c86ff959a4ce110391b/distlib-0.3.4-py2.py3-none-any.whl",
        "6564fe0a8f51e734df6333d08b8b94d4ea8ee6b99b5ed50613f731fd4089f34b",
    ),
    (
        "filelock",
        "https://files.pythonhosted.org/packages/cd/f1/ba7dee3de0e9d3b8634d6fbaa5d0d407a7da64620305d147298b683e5c36/filelock-3.6.0-py3-none-any.whl",
        "f8314284bfffbdcfa0ff3d7992b023d4c628ced6feb957351d4c48d059f56bc0",
    ),
    (
        "platformdirs",
        "https://files.pythonhosted.org/packages/de/de/d8b9da351517c3dece273224522d4714cfdb9a89e2e6f7f7f054a340cc2b/platformdirs-2.5.1-py3-none-any.whl",
        "bcae7cab893c2d310a711b70b24efb93334febe65f8de776ee320b517471e227",
    ),
    (
        "six",
        "https://files.pythonhosted.org/packages/d9/5a/e7c31adbe875f2abbb91bd84cf2dc52d792b5a01506781dbcf25c91daf11/six-1.16.0-py2.py3-none-any.whl",
        "8abb2f1d86890a2dfb989f9a77cfcfd3e47c2a354b01111771326f8aa26e0254",
    ),
    (
        "virtualenv",
        "https://files.pythonhosted.org/packages/6f/9a/1f25926bd1f9a87432938829df9e1af3a85d1f55c5a4c382217e60d63aeb/virtualenv-20.13.3-py2.py3-none-any.whl",
        "dd448d1ded9f14d1a4bfa6bfc0c5b96ae3be3f2d6c6c159b23ddcfd701baa021",
    ),
    (
        "virtualenv-clone",
        "https://files.pythonhosted.org/packages/21/ac/e07058dc5a6c1b97f751d24f20d4b0ec14d735d77f4a1f78c471d6d13a43/virtualenv_clone-0.5.7-py3-none-any.whl",
        "44d5263bceed0bac3e1424d64f798095233b64def1c5689afa43dc3223caf5b0",
    ),

    # (
    #     "pypi__click",
    #     "https://files.pythonhosted.org/packages/76/0a/b6c5f311e32aeb3b406e03c079ade51e905ea630fc19d1262a46249c1c86/click-8.0.1-py3-none-any.whl",
    #     "fba402a4a47334742d782209a7c79bc448911afe1149d07bdabdf480b3e2f4b6",
    # ),
    # (
    #     "pypi__colorama",
    #     "https://files.pythonhosted.org/packages/44/98/5b86278fbbf250d239ae0ecb724f8572af1c91f4a11edf4d36a206189440/colorama-0.4.4-py2.py3-none-any.whl",
    #     "9f47eda37229f68eee03b24b9748937c7dc3868f906e8ba69fbcbdd3bc5dc3e2",
    # ),
    # (
    #     "pypi__pip",
    #     "https://files.pythonhosted.org/packages/47/ca/f0d790b6e18b3a6f3bd5e80c2ee4edbb5807286c21cdd0862ca933f751dd/pip-21.1.3-py3-none-any.whl",
    #     "78cb760711fedc073246543801c84dc5377affead832e103ad0211f99303a204",
    # ),
    # (
    #     "pypi__pip_tools",
    #     "https://files.pythonhosted.org/packages/6d/16/75d65bdccd48bb59a08e2bf167b01d8532f65604270d0a292f0f16b7b022/pip_tools-5.5.0-py2.py3-none-any.whl",
    #     "10841c1e56c234d610d0466447685b9ea4ee4a2c274f858c0ef3c33d9bd0d985",
    # ),
    # (
    #     "pypi__pkginfo",
    #     "https://files.pythonhosted.org/packages/77/83/1ef010f7c4563e218854809c0dff9548de65ebec930921dedf6ee5981f27/pkginfo-1.7.1-py2.py3-none-any.whl",
    #     "37ecd857b47e5f55949c41ed061eb51a0bee97a87c969219d144c0e023982779",
    # ),
    # (
    #     "pypi__setuptools",
    #     "https://files.pythonhosted.org/packages/a2/e1/902fbc2f61ad6243cd3d57ffa195a9eb123021ec912ec5d811acf54a39f8/setuptools-57.1.0-py3-none-any.whl",
    #     "ddae4c1b9220daf1e32ba9d4e3714df6019c5b583755559be84ff8199f7e1fe3",
    # ),
    # (
    #     "pypi__wheel",
    #     "https://files.pythonhosted.org/packages/65/63/39d04c74222770ed1589c0eaba06c05891801219272420b40311cd60c880/wheel-0.36.2-py2.py3-none-any.whl",
    #     "78b5b185f0e5763c26ca1e324373aadd49182ca90e825f7853f4b2509215dc0e",
    # ),
]

_GENERIC_WHEEL = """\
package(default_visibility = ["//visibility:public"])

load("@rules_python//python:defs.bzl", "py_library")

py_library(
    name = "lib",
    srcs = glob(["**/*.py"]),
    data = glob(["**/*"], exclude=["**/*.py", "**/* *", "BUILD", "WORKSPACE"]),
    # This makes this directory a top-level in the python import
    # search path for anything that depends on this.
    imports = ["."],
)
"""


def _repository(name):
    return "pypi_{}".format(name)


def requirement(name):
    return "@{}//:lib".format(_repository(name))


# Collate all the repository names so they can be easily consumed
all_requirements = [_repository(name) for (name, _, _) in _RULE_DEPS]


def pipenv_install_internal_dependencies():
    """
    Fetch dependencies these rules depend on. Workspaces that use the pip_install rule can call this.

    (However we call it from pip_install, making it optional for users to do so.)
    """
    for (name, url, sha256) in _RULE_DEPS:
        maybe(
            http_archive,
            "pypi_{}".format(name),
            url = url,
            sha256 = sha256,
            type = "zip",
            build_file_content = _GENERIC_WHEEL,
        )
